FROM node:20 AS builder

WORKDIR /app

COPY package*.json ./
RUN npm install --omit=dev

COPY . .

COPY prisma ./prisma
RUN npx prisma generate

RUN npm run build

FROM node:20 AS runner

WORKDIR /app

COPY --from=builder /app/dist ./dist
COPY --from=builder /app/node_modules ./node_modules
COPY package*.json ./package.json

EXPOSE 3000
CMD ["node", "dist/src/main.js"]